name: 'Setup LilyPond'
description: 'Setup a LilyPond environemnt and add it to the PATH'
author: 'Codello'

# TODO: Maybe support setting the language, default log level
inputs:
  lilypond-version:
    required: true
    description:
      'The LilyPond version to download and use. Supports semver spec and
      ranges.'
  ol-fonts:
    description: 'A comma separated list of OpenLilyPondFonts to install.'

outputs:
  lilypond-version:
    description:
      'The installed LilyPond version. Useful when given a version range as
      input.'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: music
  color: green
